---
- name: Add Remote Desktop Feature
  win_feature:
    name: Remote-Desktop-Services
    state: present
  register: rds_install

- name: Add additional Features
  win_feature:
    name: 
    - RSAT-Role-Tools
    - RSAT-AD-Tools
    - RSAT-ADDS-Tools
    state: present

- name: Reboot 
  ansible.windows.win_reboot:
  when: rds_install.reboot_required