- name: move computer to ou
  ansible.windows.win_powershell:
    script: |
      Get-ADComputer $env:computername| Move-ADObject -TargetPath "{{ vm_ad_ou }}"
    arguments:
    - -ExecutionPolicy
    - ByPass

- name: Set timezone to W. Europe Standard Time
  community.windows.win_timezone:
    timezone: W. Europe Standard Time

- name: Reboot
  ansible.windows.win_reboot:

- name: Wait for system to become reachable
  wait_for_connection:
    timeout: 900