- name: install git
  ansible.windows.win_powershell:
    script: |
      if (!((gp HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\*).DisplayName -Match "git" )) {
        Invoke-WebRequest 'https://github.com/git-for-windows/git/releases/download/v2.35.1.windows.2/Git-2.35.1.2-64-bit.exe' -OutFile c:\temp\gitsetup.exe
        c:\temp\gitsetup.exe /silent 
      }

- name: install vs code
  ansible.windows.win_powershell:
    script: |
      if (!((gp HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\*).DisplayName -Match "Visual Studio Code" )) {
        Invoke-WebRequest 'https://code.visualstudio.com/sha/download?build=stable&os=win32-x64' -OutFile c:\temp\VSCodeSetup.exe
        c:\temp\VSCodeSetup.exe /VERYSILENT /NORESTART /MERGETASKS=!runcode 
      }

- name: install Vmware Remote Console
  ansible.windows.win_powershell:
    script: |
      if (!((gp HKLM:\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\*).DisplayName -Match "VMware Remote Console" )) {
        & (get-childitem "{{ software_share }}\VMRC"|Sort-Object -Descending -Property LastWriteTime)[0].fullname /V /Qn EULAS_AGREED=1 AUTOSOFTWAREUPDATE=0 ATACOLLECTION=0
      }

- name: install Powershell 7.2
  ansible.windows.win_powershell:
    script: |
      Invoke-Expression "& { $(Invoke-RestMethod 'https://aka.ms/install-powershell.ps1') } –useMSI -EnablePSRemoting -Quiet"

