---
- set_fact: creationdate="{{lookup('pipe','date "+%Y/%m/%d %H:%M"')}}"

- name: Create VM
  community.vmware.vmware_guest:
    hostname: '{{ vcenter_hostname }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    datacenter: '{{ vm_datacenter }}'
    cluster: '{{ vm_cluster }}'
    folder: '{{ vm_folder }}'
    name: '{{ item }}'
    resource_pool: '{{ vm_resource_pool }}'
    template: '{{ vm_template }}'
    validate_certs: 'no'
    state: 'poweredon'
    annotation: "{{ notes }} \n deployed by ansible at: {{ creationdate }}"
    disk:
      - size_gb: '{{ vm_disk1 }}'
        controller_number: 0
        controller_type: lsilogicsas
        unit_number: 0
        type: '{{ vm_disktype }}'
        datastore: '{{ vm_datastore }}'
      - size_gb: '{{ vm_disk2 }}'
        controller_type: lsilogicsas
        controller_number: 0
        unit_number: 1
        type: '{{ vm_disktype }}'
        datastore: '{{ vm_datastore }}'
    hardware:
      memory_mb: '{{ vm_memory | int * 1024 }}'
      num_cpus: '{{ vm_cpucount }}'
    networks:
    - name: '{{ vm_network }}'
      type: 'dhcp'
    customization:
      hostname: '{{ item | lower }}'
      domain: '{{ domain }}'
      domainadmin: "{{ vcenter_username }}@{{ domain }}"
      joindomain: '{{ domain }}'
      domainadminpassword: '{{ vcenter_password }}' 
      dns_suffix: '{{ domain }}'
      dns_servers: '{{ vm_dns_server }}'
      fullname: '--'
      orgname: '--'
    wait_for_ip_address: 'yes'
    wait_for_customization: 'yes'
  delegate_to: 'localhost'
  with_items: "{{ servers }}"

- name: Add host to group 'rdp_hosts'
  add_host:
    name: '{{ item }}.{{ domain }}'
    ansible_connection: ssh
    ansible_shell_type: cmd
    ansible_user: "{{ vcenter_username }}@{{ domain }}"
    ansible_ssh_pass: '{{ vcenter_password }}'
    groups: 'rdp_hosts'
  with_items: "{{ servers }}"

- name: Wait for system to become reachable
  wait_for_connection:
    timeout: 900

- name: accept new ssh fingerprints
  shell: ssh-keyscan {{ item }}.{{ domain }} >> ~/.ssh/known_hosts
  with_items: "{{ servers }}"
  delegate_to: localhost

